services:
  - type: web
    name: lobo-cordero
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn lobocordero.conexion:app --worker-tmp-dir /dev/shm --timeout 120
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///corrupt.db
